---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Install required packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages|default([]) }}"

- name: Install Java
  include_tasks: java.yml
  when: java != "embedded"

- name: Make sure the NTP service is started
  service:
    name: "{{ ntp_service_name }}"
    state: started

- name: Make sure the NTP service is enabled
  service:
    name: "{{ ntp_service_name }}"
    enabled: yes
  ignore_errors: true

- name: Add mappings to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item]['ansible_'~hostvars[item].ansible_default_ipv4.alias]['ipv4']['address'] }}.*"
    line: "{{ hostvars[item]['ansible_'~hostvars[item].ansible_default_ipv4.alias]['ipv4']['address'] }} {{ hostvars[item]['ansible_nodename'] }}"
    insertafter: "^127..*$"
    state: present
  with_items:
    - "{{ groups['hadoop-cluster']|sort(reverse=True) }}"
  when: not external_dns

- name: Make sure /etc/security/limits.d exists
  file:
    path: /etc/security/limits.d
    mode: 0755
    state: directory

- name: Set nofile and nproc limits
  blockinfile:
    path: /etc/security/limits.d/99-hadoop.conf
    create: yes
    mode: 0644
    block: |
      * soft nofile 32768
      * hard nofile 32768
      * soft nproc 32768
      * hard nproc 32768
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Set swappiness to {{ swappiness }}
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    state: present
    reload: yes
    ignoreerrors: yes

- block:
    - name: Stop the {{ firewall_service_name }} firewall service
      service:
        name: "{{ firewall_service_name }}"
        state: stopped
      ignore_errors: true

    - name: Disable the {{ firewall_service_name }} firewall service
      service:
        name: "{{ firewall_service_name }}"
        enabled: no
      ignore_errors: true
  when: disable_firewall

- name: Disable selinux
  selinux:
    state: disabled
  when: ansible_os_family|lower == "redhat" and ansible_distribution|lower != "amazon"

- name: Disable Transparent Huge Pages until the next reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  args:
    removes: /sys/kernel/mm/transparent_hugepage/enabled

- name: Disable Transparent Huge Pages in Grub 2
  lineinfile:
    path: /etc/default/grub
    state: present
    line: 'GRUB_CMDLINE_LINUX=$GRUB_CMDLINE_LINUX" transparent_hugepage=never"'
  when: (ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int == 7) or (ansible_os_family|lower == "debian" and ansible_distribution_major_version|int >= 7) or (ansible_os_family|lower == "suse" and ansible_distribution_major_version|int == 12)

  notify: Generate the Grub config file

- meta: flush_handlers

- name: Configure tuned (RHEL/CentOS 7)
  include_tasks: tuned.yml
  when: ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int == 7

- block:
    - name: Attempt to fetch the http secret key
      fetch:
        src: /etc/security/http_secret
        dest: /tmp/hadoop_http_secret
        flat: yes
      delegate_to: "{{ groups['ambari-server']|sort|list|first }}"
      run_once: true
      register: fetch_results

    - name: Create the http secret key
      local_action: shell dd if=/dev/urandom of=/tmp/hadoop_http_secret bs=1024 count=1
      run_once: true
      become: false
      args:
        creates: /tmp/hadoop_http_secret
      when: not fetch_results.changed

    - name: Copy the http secret key to all nodes
      copy:
        src: /tmp/hadoop_http_secret
        dest: /etc/security/http_secret
        force: yes
        mode: 0444

    - name: Delete the http secret key
      local_action: file path="/tmp/hadoop_http_secret" state="absent"
      run_once: true
      become: false
  when: security != "none" and security_options.http_authentication|default(false)
