---
- name: Create tuned directory
  file:
    path: /etc/tuned/hdp/
    state: directory

- name: Upload the tuned profile
  template:
    src: tuned.conf.j2
    dest: /etc/tuned/hdp/tuned.conf
    mode: 0755

- name: Activate the tuned profile
  shell: tuned-adm profile hdp
