---
hdp_main_repo_url: "{{ base_url }}/HDP/centos6/{{ hdp_major_version }}.x/updates/{{ hdp_version }}"
hdf_main_repo_url: "{{ base_url }}/HDF/centos6/{{ hdf_major_version }}.x/updates/{{ hdf_version }}"
main_os_target: "operating_systems/redhat6"

utils_repo_url: "{{ base_url }}/HDP-UTILS-{{ utils_version }}/repos/centos6"
utils_os_target: "operating_systems/redhat6/repositories/HDP-UTILS-{{ utils_version }}"
