---
packages:
  - openssh-clients         # scp required by Ambari
  - curl                    # curl required by Ambari
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - chrony                  # ntp required by Hadoop
  - openssl-devel           # openssl-devel recommended for Ranger KMS
  - libtirpc-devel          # libtirpc required by HDP 2.6+
  - libselinux-python       # libselinux-python required by Ansible

openjdk_package: java-1.8.0-openjdk-devel

ntp_service_name: chronyd

update_grub_command: 'grub2-mkconfig -o "$(readlink -n /etc/grub2.cfg)"'
