---
packages:
  - python27-httplib2       # required for calling Ambari API from Ansible
  - openssh-clients         # scp required by Ambari
  - curl                    # curl required by Ambari
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - ntp                     # ntp required by Hadoop

openjdk_package: java-1.8.0-openjdk-devel

ntp_service_name: ntpd

firewall_service_name: iptables

epel_url: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
