---
packages:
  - openssh                 # scp required by Ambari
  - curl                    # curl required by Ambari
  - php53-curl              # php-curl requred by Ambari in SLES
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - ntp                     # ntp required by Hadoop

ntp_service_name: ntp

firewall_service_name: SuSEfirewall2_setup
