---
- name: Build the Cloud Environment
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../../inventory/openstack/group_vars/all
  tasks:
    - name: Build Openstack Nodes
      include: build_openstack_nodes.yml
      when: item.count > 0
      with_items: "{{ nodes }}"
