---
kdc_packages:
  - krb5-kdc
  - krb5-admin-server
  - krb5-user
kdc_service_name: krb5-kdc
kadmin_service_name: krb5-admin-server

kdc_init_command: kdb5_util create -s -W
kadmin_command: kadmin.local

kdc_config_file: /etc/krb5kdc/kdc.conf
kdc_acl_file: /etc/krb5kdc/kadm5.acl
kdc_database_file: /var/lib/krb5kdc/principal
