---
kdc_packages:
  - krb5-server
  - krb5-libs
  - krb5-workstation
kdc_service_name: krb5kdc
kadmin_service_name: kadmin

kdc_init_command: kdb5_util create -s -W
kadmin_command: kadmin.local

kdc_config_file: /var/kerberos/krb5kdc/kdc.conf
kdc_acl_file: /var/kerberos/krb5kdc/kadm5.acl
kdc_database_file: /var/kerberos/krb5kdc/principal
