---
openjdk_path: /usr/lib64/jvm/java-1.8.0-openjdk

postgres_packages:
  - postgresql96
  - postgresql-jdbc
postgres_jdbc_location: /usr/share/java/postgresql-jdbc.jar

mysql_packages:
  - python-mysql
  - mysql-connector-java
mysql_jdbc_location: /usr/share/java/mysql-connector-java.jar
