---
- set_fact: outer_loop="{{ item }}"

- name: Add nodes to hadoop-cluster group
  add_host:
    name: "{{ hostvars[local_loop].name }}"
    ansible_host: "{{ (outer_loop.public_ip|default(false)== true) | ternary(hostvars[local_loop].public_ip,hostvars[local_loop].private_ip) }}"
    ansible_ssh_host: "{{ (outer_loop.public_ip|default(false)== true) | ternary(hostvars[local_loop].public_ip,hostvars[local_loop].private_ip) }}"
    ansible_user: "{{ cloud_config.admin_username|default('root') }}"
    ansible_ssh_private_key_file: "{{ cloud_config.ssh.privatekey }}"
    ansible_become_user: root
    groups: hadoop-cluster
  loop_control:
    loop_var: local_loop
  with_items: "{{ groups['group_'~outer_loop.group] }}"

- name: Add nodes to {{ outer_loop.group }} group
  add_host:
    name: "{{ hostvars[local_loop].name }}"
    ansible_host: "{{ (outer_loop.public_ip|default(false)== true) | ternary(hostvars[local_loop].public_ip,hostvars[local_loop].private_ip) }}"
    ansible_ssh_host: "{{ (outer_loop.public_ip|default(false)== true) | ternary(hostvars[local_loop].public_ip,hostvars[local_loop].private_ip) }}"
    ansible_user: "{{ cloud_config.admin_username|default('root') }}"
    ansible_ssh_private_key_file: "{{ cloud_config.ssh.privatekey }}"
    ansible_become_user: root
    groups: "{{ outer_loop.group }}"
  loop_control:
    loop_var: local_loop
  with_items: "{{ groups['group_'~outer_loop.group] }}"

- name: Add node to ambari-server group
  add_host:
    name: "{{ hostvars[local_loop].name }}"
    ansible_host: "{{ (outer_loop.public_ip|default(false)== true) | ternary(hostvars[local_loop].public_ip,hostvars[local_loop].private_ip) }}"
    ansible_ssh_host: "{{ (outer_loop.public_ip|default(false)== true) | ternary(hostvars[local_loop].public_ip,hostvars[local_loop].private_ip) }}"
    ansible_user: "{{ cloud_config.admin_username|default('root') }}"
    ansible_ssh_private_key_file: "{{ cloud_config.ssh.privatekey }}"
    ansible_become_user: root
    groups: ambari-server
  loop_control:
    loop_var: local_loop
  when: outer_loop.ambari_server is defined and outer_loop.ambari_server
  with_items: "{{ groups['group_'~outer_loop.group] }}"
